version: '3.1'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3307:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=colores
           - MYSQL_DATABASE=bd_color
           - MYSQL_USER=root
           - MYSQL_PASSWORD=  
           - MYSQL_ROOT_HOST=127.0.0.1
    volumes:
           - ./my-datavolume:/var/lib/mysql
           - ./datos.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always

  color-service:
    build: ./BACKEND/colors-services
    
    ports:
           - "8084:8084"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ./FRONTEND/COLOR-frontend
    ports:
           - "8082:80"  